
permissions:
  contents: write
  
name: CI/CD for Dev Environment

on:
  push:
    branches: 
      - main

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - run: npm ci

      - run: npm run build --if-present

      - run: npm start

  deploy-dev:
    runs-on: ubuntu-latest
    needs: build
    environment: dev

    steps:
      - name: Deploy to Dev
        run: |
          echo "Deploying to Dev environment..."
          # Use environment secrets here
          echo "Using secret key: ${{ secrets.YOUR_SECRET_NAME }}"
          # Add your deployment script or command here
